[2019-10-25 14:51:22,480][__main__][INFO] - The server is running...
[2019-10-25 14:51:34,101][grpc._server][ERROR] - Exception calling application: name 'automatic_annotator_pb2' is not defined
Traceback (most recent call last):
  File "/home/adrian/miniconda3/envs/julia/lib/python3.7/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "automatic_annotator_server.py", line 19, in Annotate
    msg = automatic_annotator_pb2.AnnotateResponse()
NameError: name 'automatic_annotator_pb2' is not defined
